### PR TITLE
update tos-informativa to version 2.5

### PR DESCRIPTION
**Pull request by CaraDune**
this pr: 
- updates privacy policy and terms of service to version 2.5 governing new opt-in mechanism for services;
- is reviewed and approved by the Design Team and the Legal Team of the app developer.

**Dev team please double check indentation, spaces and markdown section tags**

### CODE REVIEW

**Comment by vito80ba** [comment]
Ref to new PR with some integrations, please #347

**Review by Undermaken — CHANGES_REQUESTED** [review]

**Comment by vito80ba** [comment]
Please, use the #347 instead

**Comment by CaraDune** [comment]
commento di prova - ignorare
lorem ipsum dolor sit amet

**Comment by CaraDune** [comment]
commento di prova 2 - ignorare

lorem ipsum dolor sit amet

**Pull request closed without merging**
